### ISSUE TITLE
Start values in PDETime_massFlow

### ISSUE THREAD

**Issue by marcusfuchs** [bramvdh91/modelica-annex60#44]
In one of my applications, I see significant speed-ups for initialization and simulation just be setting `start=0` for `tau`, `inp_a` and `inp_b` in `PDETime_massFlow`. I'll push this to a branch and will issue a PR. If this has no negative effects for anyone else, I think this is a useful improvement.

**Comment by bramvdh91** [comment]
I was just thinking about the same, since I always get a warning that this value is not initialized and hence set to 0. Maybe it would be more logical, at least if a starting value for the mass flow is known, to set `tau` to `length/v`, but I guess the proposed solution is more than adequate. 

Closed by #45
